# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7daa5c93948f34eaab517144b7f16dbb39333371370c5731a6c5b9c465bf10e32a3f61fb5787b6f17bd05a01bade5f255906ec2fe7b3cc910dfdffab1ab876b3

test:
  secret_key_base: 1be54e4e3cb1009d0706f2302a381d6e91986c3ef644c759d397f53d99e5c012ce70c43a8a36791b5940dc8ccd2a84329cd34213677d9f2dc6a1962a19946da6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
